# Generated by Django 3.1.1 on 2020-09-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200912_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palette',
            old_name='user',
            new_name='user_id',
        ),
    ]
